# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dexseq_count"
description: |
  Count exons using the dexseq_count.py script from the DEXSeq package. This script takes as input a sorted BAM file and a GFF file containing the exon annotations, and outputs a tab-delimited text file containing the counts for each exon.
keywords:
  - dexseq
  - count
  - exon
  - rnaseq
tools:
  - "htseq":
      description: "HTSeq is a Python library to facilitate processing and analysis
        of data from high-throughput sequencing (HTS) experiments."
      homepage: "https://htseq.readthedocs.io/en/latest"
      documentation: "https://htseq.readthedocs.io/en/latest"
      tool_dev_url: "https://github.com/htseq/htseq"
      doi: "10.1093/bioinformatics/btac166"
      licence: ["GPL v3"]
      identifier: biotools:htseq

input:
  - - meta:
        type: map
        description: |
          A map containing the metadata for the input files.
    - bam:
        type: file
        description: |
          A sorted BAM file containing the aligned reads. This file will be used as input for the counting step of the DEXSeq pipeline.
        pattern: "*.bam"
        ontologies:
          - edam: "http://edamontology.org/format_2572"
    - gff:
        type: file
        description: |
          A GFF file containing the exon annotations. This file will be used as input for the counting step of the DEXSeq pipeline.
        pattern: "*.gff"
        ontologies:
          - edam: "http://edamontology.org/format_3673"
  - - alignment_quality:
        type: float
        description: |
          A float value representing the quality of the alignment. This value can be used to filter out low-quality alignments before counting.

output:
  dexseq_clean_txt:
    - - meta:
          type: map
          description: |
            A map containing the metadata for the output files.
      - "*.clean.counts.txt":
          type: file
          description: |
            A tab-delimited text file containing the counts for each exon. This file will be used as input for the downstream analysis of the DEXSeq pipeline.
          pattern: "*.clean.counts.txt"
  versions_htseq:
    - - "${task.process}":
          type: string
          description: The name of the process
      - "htseq":
          type: string
          description: The name of the tool
      - 'python -c "import HTSeq; print(HTSeq.__version__)"':
          type: eval
          description: The expression to obtain the version of the tool

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - htseq:
          type: string
          description: The name of the tool
      - python -c "import HTSeq; print(HTSeq.__version__)":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Keerthana-Bhaskaran-TG"
  - "@bensouthgate"
