# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dexseq_annotation"
description: "Module to annotate sorted BAM/CRAM/SAM files using DEXSeq."
keywords:
  - RNA-seq
  - differential exon usage
  - annotation
tools:
  - "htseq":
      description: "HTSeq is a Python library to facilitate processing and analysis
        of data from high-throughput sequencing (HTS) experiments."
      homepage: "https://htseq.readthedocs.io/en/latest"
      documentation: "https://htseq.readthedocs.io/en/latest"
      tool_dev_url: "https://github.com/htseq/htseq"
      doi: "10.1093/bioinformatics/btac166"
      licence: ["GPL v3"]
      identifier: biotools:htseq

input:
  - gtf:
      type: file
      description: GTF file
      pattern: "*.{gtf}"
      ontologies:
        - edam: http://edamontology.org/format_1777 # GTF
  - aggregation:
      type: boolean
      description: |
        Whether to aggregate counts for exons that belong to the same gene. If true, the output will contain one row per gene, with the counts for all exons in that gene aggregated together. If false, the output will contain one row per exon.

output:
  gff:
    - "*.gff":
        type: file
        description: GFF file
        pattern: "*.{gff}"
        ontologies:
          - edam: http://edamontology.org/format_1778
  versions_htseq:
    - - ${task.process}:
          type: string
          description: The name of the process
      - htseq:
          type: string
          description: The name of the tool
      - python -c "import HTSeq; print(HTSeq.__version__)":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - htseq:
          type: string
          description: The name of the tool
      - python -c "import HTSeq; print(HTSeq.__version__)":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@Keerthana-Bhaskaran-TG"
