# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dexseq_dtu"
description: |
  Differential transcript usage analysis using DEXSeq. This module performs differential transcript usage analysis using the DEXSeq package in R.
keywords:
  - dexseq
  - differential transcript usage
  - rnaseq
  - alternative splicing
tools:
  - "bioconductor-dexseq":
      description: "Inference of differential exon usage in RNA-Seq"
      homepage: "https://bioconductor.org/packages/release/bioc/html/DEXSeq.html"
      documentation: "https://bioconductor.org/packages/release/bioc/html/DEXSeq.html"
      tool_dev_url: "https://github.com/Huber-group-EMBL/DEXSeq"
      doi: "10.18129/B9.bioc.DEXSeq"
      licence: ["GPL >=3"]
      identifier: "biotools:dexseq"

input:
  - drimseq_sample_data:
      type: file
      description: |
        Input file containing the sample data for the DEXSeq analysis. This file should be in a tab-delimited format and contain the following columns: sample, condition and sequencing data path.
      pattern: "*.{csv}"
  - drimseq_d_counts:
      type: file
      description: |
        Input file containing the count data for the DEXSeq analysis. This file should be in a tab-delimited format and contain the following columns: gene_id, exon_id, sample and count.
      pattern: "*.{tsv}"
  - drimseq_contrast_data:
      type: file
      description: |
        Input file containing the contrast data for the DEXSeq analysis. This file should be in a tab-delimited format and contain the following columns: condition and contrast.
      pattern: "*.{csv}"
output:
  dexseq_exon_dataset_rds:
    - "DEXSeqDataSet.*.rds":
        type: file
        description: RDS file containing the DEXSeq exon dataset
        pattern: "*.{rds}"
  dexseq_exon_results_rds:
    - "DEXSeqResults.*.rds":
        type: file
        description: RDS file containing the DEXSeq exon results
        pattern: "*.{rds}"
  dexseq_exon_results_tsv:
    - "DEXSeqResults.*.tsv":
        type: file
        description: TSV file containing the DEXSeq exon results
        pattern: "*.{tsv}"
  dexseq_gene_results_rds:
    - "perGeneQValue.*.rds":
        type: file
        description: RDS file containing the DEXSeq per gene q-value results
        pattern: "*.{rds}"
  dexseq_gene_results_tsv:
    - "perGeneQValue.*.tsv":
        type: file
        description: TSV file containing the DEXSeq per gene q-value results
        pattern: "*.{tsv}"
  versions_R:
    - - ${task.process}:
          type: string
          description: The name of the process
      - r-base:
          type: string
          description: The name of the tool
      - R --version 2>&1 | head -n 1 | sed "s/^.*version //; s/ .*$//":
          type: eval
          description: The expression to obtain the version of R
  versions_dexseq:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bioconductor-dexseq:
          type: string
          description: The name of the tool
      - Rscript -e "library(DEXSeq); cat(as.character(packageVersion(\'DEXSeq\')))":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - bioconductor-dexseq:
          type: string
          description: The name of the tool
      - Rscript -e "library(DEXSeq); cat(as.character(packageVersion(\'DEXSeq\')))":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - r-base:
          type: string
          description: The name of the tool
      - R --version 2>&1 | head -n 1 | sed "s/^.*version //; s/ .*$//":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@bensouthgate"
