# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "clustergroups"
description: "Utility module to cluster samples based on a column value. This is used to cluster samples based on the TPM matrix."
keywords:
  - alternative splicing
  - suppa
  - genomics
  - helper
tools:
  - "clustergroups":
      homepage: "https://github.com/nf-core/rnasplice"
      description: ""
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing contrast information
          e.g. `[ id:'contrast1' ]`
    - cond1:
        type: string
        description: Condition 1 for clustering
    - cond2:
        type: string
        description: Condition 2 for clustering
    - psivec:
        type: file
        description: SUPPA PSI vector file
        pattern: "*.psivec"
        ontologies: []

output:
  groups:
    - - meta:
          type: map
          description: |
            Groovy Map containing contrast information
            e.g. `[ id:'contrast1' ]`
      - cond1:
          type: string
          description: Condition 1 for clustering
      - cond2:
          type: string
          description: Condition 2 for clustering
      - "*_groups.txt":
          type: file
          description: Clustered groups file
          pattern: "*_groups.txt"
          ontologies: []
  versions_python:
    - "versions.yml":
        type: file
        description: Versions file for python

topics:
  versions:
    - "versions.yml":
        type: file
        description: Versions file for python
        pattern: "versions.yml"
authors:
  - "@jma1991"
  - "@piplus2"
maintainers:
  - "@piplus2"
